export const Questions = {
  level1: [
    "How many fingers are on your right hand",
    "how many eyes you have",
    "how many nose you have",
    "how many legs you have",
    "how many fingers are there in your both hands",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of boys present",
    "select ten form below",
    "select two from below",
    "select nine from below",
    "select seven from below",
    "what is one added to one ",
    "find direction of arrow ⬆️",
    "find direction of arrow ⬇️",
    "find the direction of arrow ⬅️",
    "find the direction of arrow ➡️",
    "which hand you use for eating",
  ],
  level2: [
    "How many toes do you have in both legs",
    "What is 2 + 3 ?",
    "What is 3 + 5 ?",
    "What is 1 + 1 ?",
    "What is 4 + 6 ?",
    "count the number of balls present ?",
    "count the number of balls present ?",
    "count the number of balls present",
    "What is the total number of slices of bread in the picture below?",
    "A tray of cookies has 10 cookies on it. If 4 cookies are eaten, how many cookies are left on the tray?",
    "select twenty seven from below",
    "select seventy two from below",
    "select thirty nine from below",
    "select seventy nine from below",
    "what is twenty added to nineteen ",
    "What is the color of sky?",
    "What is the color of grass?",
    "What is the color of rose",
    "What is the color of elephant",
    "What is the color of cucumber",
  ],
  level3: [
    "A basket contains 6 apples. If 4 more apples are added, how many apples are in the basket?",
    "Sarah has 15 toy cars her brother gave 4 more to her. How many toy cars will she have left?",
    "Johnny has 13 baseball cards and his friend gives him 6 more. How many baseball cards does Johnny have now?",
    "What is the greatest two digit number?",
    "Rahul has 3 red balls and 8 blue balls. How many balls does he have in total?",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of boys present",
    "select three hundred fifty two from below",
    "select two hundred fifty three from below",
    "select five hundred thirty two from below",
    "select three hundred and thirty two from below",
    "select the smallest number ",
    "what is 13 + 17",
    "what is 41 + 32",
    "what is 12 + 11",
    "what is 10 + 16",
    "what is 53 + 20",
  ],
  level4: [
    "John distributed 6 chocolates to 3 friends each, how much did John distribute in total?",
    "what is the greatest two digit number before 103",
    "what is the lowest two digit number after 92",
    "Rahul has 20 chocolates, he ate 4 and gave 6 to his sister. How much does he have left",
    "Ram was 16 two years ago, what is his current age?",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of boys present",
    "select one thousand two hundred and fourty one from below",
    "select four tousand two hundred and eleven from below",
    "select two thousand one hundred and forty one from below",
    "select one thousand four hundred and twenty one from below",
    "what is 1250 - 9 ",
    "find direction opposite of arrow ⬆️",
    "find direction opposite of arrow ⬇️",
    "find the direction opposite of arrow ⬅️",
    "find the direction opposite of arrow ➡️",
    "Which way do the hands of a clock move to indicate the passage of time?",
  ],
};
export const Answers = {
  level1: [
    5,
    2,
    1,
    2,
    10,
    1,
    3,
    4,
    2,
    1,
    10,
    2,
    9,
    7,
    2,
    "up",
    "down",
    "left",
    "right",
    "right",
  ],
  level2: [
    10,
    5,
    8,
    2,
    10,
    6,
    2,
    8,
    10,
    6,
    27,
    72,
    39,
    79,
    39,
    "blue",
    "green",
    "red",
    "black",
    "green",
  ],
  level3: [
    10,
    19,
    19,
    99,
    11,
    1,
    2,
    3,
    4,
    2,
    352,
    253,
    532,
    332,
    253,
    30,
    73,
    23,
    26,
    73,
  ],
  level4: [
    18,
    99,
    93,
    10,
    18,
    1,
    3,
    4,
    2,
    1,
    1241,
    4211,
    2141,
    1421,
    1241,
    "down",
    "up",
    "right",
    "left",
    "right",
  ],
};
export const Options = {
  level1: [
    0,
    0,
    0,
    0,
    0,
    ["2", "1", "5", "10"],
    0,
    0,
    0,
    0,
    ["3", "4", "2", "1"],
    0,
    0,
    0,
    0,
    ["7", "2", "9", "10"],
    0,
    0,
    0,
    0,
    ["down", "up", "right", "left"],
  ],
  level2: [
    0,
    0,
    0,
    0,
    0,
    ["5", "10", "2", "8"],
    0,
    0,
    0,
    0,
    ["2", "6", "10", "8"],
    0,
    0,
    0,
    0,
    ["39", "27", "79", "72"],
    0,
    0,
    0,
    0,
    ["red", "black", "green", "blue"],
  ],
  level3: [
    0,
    0,
    0,
    0,
    0,
    ["19", "10", "99", "11"],
    0,
    0,
    0,
    0,
    ["1", "2", "3", "4"],
    0,
    0,
    0,
    0,
    ["253", "352", "332", "532"],
    0,
    0,
    0,
    0,
    ["73", "30", "26", "23"],
  ],
  level4: [
    0,
    0,
    0,
    0,
    0,
    ["10", "99", "93", "18"],
    0,
    0,
    0,
    0,
    ["3", "4", "2", "1"],
    0,
    0,
    0,
    0,
    ["2141", "1241", "4211", "1421"],
    0,
    0,
    0,
    0,
    ["down", "up", "right", "left"],
  ],
};
