export const Questions = {
  level1: [
    "How many fingers are on your right hand",
    "how many eyes you have",
    "how many nose you have",
    "how many legs you have",
    "how many fingers are there in your both hands",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of boys present",
    "select ten form below",
    "select two from below",
    "select nine from below",
    "select seven from below",
    "what is one added to one ",
    "find direction of arrow ⬆️",
    "find direction of arrow ⬇️",
    "find the direction of arrow ⬅️",
    "find the direction of arrow ➡️",
    "which hand you use for eating",
  ],
  level2: [
    "How many fingers are on your right hand",
    "how many eyes you have",
    "how many nose you have",
    "how many legs you have",
    "how many fingers are there in your both hands",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of boys present",
    "select ten form below",
    "select two from below",
    "select nine from below",
    "select seven from below",
    "what is one added to one ",
    "find direction of arrow ⬆️",
    "find direction of arrow ⬇️",
    "find the direction of arrow ⬅️",
    "find the direction of arrow ➡️",
    "which hand you use for eating",
  ],
  level3: [
    "How many fingers are on your right hand",
    "how many eyes you have",
    "how many nose you have",
    "how many legs you have",
    "how many fingers are there in your both hands",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of boys present",
    "select ten form below",
    "select two from below",
    "select nine from below",
    "select seven from below",
    "what is one added to one ",
    "find direction of arrow ⬆️",
    "find direction of arrow ⬇️",
    "find the direction of arrow ⬅️",
    "find the direction of arrow ➡️",
    "which hand you use for eating",
  ],
  level4: [
    "How many fingers are on your right hand",
    "how many eyes you have",
    "how many nose you have",
    "how many legs you have",
    "how many fingers are there in your both hands",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of balls present",
    "count the number of boys present",
    "select ten form below",
    "select two from below",
    "select nine from below",
    "select seven from below",
    "what is one added to one ",
    "find direction of arrow ⬆️",
    "find direction of arrow ⬇️",
    "find the direction of arrow ⬅️",
    "find the direction of arrow ➡️",
    "which hand you use for eating",
  ],
};
export const Answers = {
  level1: [
    5,
    2,
    1,
    2,
    10,
    1,
    3,
    4,
    2,
    1,
    10,
    2,
    9,
    7,
    2,
    "up",
    "down",
    "left",
    "right",
    "right",
  ],
  level2: [
    5,
    2,
    1,
    2,
    10,
    1,
    3,
    4,
    2,
    1,
    10,
    2,
    9,
    7,
    2,
    "up",
    "down",
    "left",
    "right",
    "right",
  ],
  level3: [
    5,
    2,
    1,
    2,
    10,
    1,
    3,
    4,
    2,
    1,
    10,
    2,
    9,
    7,
    2,
    "up",
    "down",
    "left",
    "right",
    "right",
  ],
  level4: [
    5,
    2,
    1,
    2,
    10,
    1,
    3,
    4,
    2,
    1,
    10,
    2,
    9,
    7,
    2,
    "up",
    "down",
    "left",
    "right",
    "right",
  ],
};
export const Options = {
  level1: [
    0,
    0,
    0,
    0,
    0,
    ["2", "1", "5", "10"],
    0,
    0,
    0,
    0,
    ["3", "4", "2", "1"],
    0,
    0,
    0,
    0,
    ["7", "2", "9", "10"],
    0,
    0,
    0,
    0,
    ["down", "up", "right", "left"],
  ],
  level2: [
    0,
    0,
    0,
    0,
    0,
    ["2", "1", "5", "10"],
    0,
    0,
    0,
    0,
    ["3", "4", "2", "1"],
    0,
    0,
    0,
    0,
    ["7", "2", "9", "10"],
    0,
    0,
    0,
    0,
    ["down", "up", "right", "left"],
  ],
  level3: [
    0,
    0,
    0,
    0,
    0,
    ["2", "1", "5", "10"],
    0,
    0,
    0,
    0,
    ["3", "4", "2", "1"],
    0,
    0,
    0,
    0,
    ["7", "2", "9", "10"],
    0,
    0,
    0,
    0,
    ["down", "up", "right", "left"],
  ],
  level4: [
    0,  
    0,
    0,
    0,
    0,
    ["2", "1", "5", "10"],
    0,
    0,
    0,
    0,
    ["3", "4", "2", "1"],
    0,
    0,
    0,
    0,
    ["7", "2", "9", "10"],
    0,
    0,
    0,
    0,
    ["down", "up", "right", "left"],
  ],
};
